title: GONDOLA
default_lang: en
author:
  name: GONDOLA
taxonomies:
  - category
  - tag
metadata:
  description: ''
  keywords: ''
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
