title: MOWEDE
default_lang: en
author:
  name: MOWEDE
taxonomies:
  - category
  - tag
metadata:
  description: 'MOWEDE is your one-stop shop for app development and maintenance. Our developers will create apps with all the functionality you need to be successful.'
  keywords: 'MOWEDE, software application development services, app development and maintenance, app development services, app development and maintenance, mobile app, create apps, develop apps, web development, desktop development, modernize legacy applications'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
